In [14]:
from Data_procesing import data_process
print('Hello you')
file_path = 'C:/Users/Ghassen/Documents/Projects/Immobilier/1_Project/Data_assets/Brut/valeursfoncieres-2019.txt'
df = data_process.read_clean_process(file_path)
print(len(df))
df.head()

Hello you
2535791

,No_disposition,Date_mutation,Nature_mutation,Valeur_fonciere,No_voie,Type_de_voie,Voie,Code_postal,Commune,Code_departement,...,5eme_lot,Surface_Carrez_du_5eme_lot,Nombre_de_lots,Code_type_local,Type_local,Surface_reelle_bati,Nombre_pieces_principales,Nature_culture,Nature_culture_speciale,Surface_terrain
0,1,2019-04-01,Vente,37220.0,26.0,RUE,DE MONTHOLON,1000.0,BOURG-EN-BRESSE,01,...,NaN,NaN,1,2.0,Appartement,20.0,1.0,NaN,NaN,NaN
1,1,2019-04-01,Vente,185100.0,22.0,RUE,GEN DELESTRAINT,1000.0,BOURG-EN-BRESSE,01,...,NaN,NaN,2,2.0,Appartement,62.0,3.0,NaN,NaN,NaN
2,1,2019-04-01,Vente,185100.0,22.0,RUE,GEN DELESTRAINT,1000.0,BOURG-EN-BRESSE,01,...,NaN,NaN,1,3.0,Dépendance,0.0,0.0,NaN,NaN,NaN
3,1,2019-08-01,Vente,209000.0,3.0,RUE,DES CHAMPAGNES,1160.0,PRIAY,01,...,NaN,NaN,0,1.0,Maison,90.0,4.0,S,NaN,940.0
4,1,2019-07-01,Vente,134900.0,5.0,LOT,LE BIOLAY,1370.0,SAINT-ETIENNE-DU-BOIS,01,...,NaN,NaN,0,1.0,Maison,101.0,5.0,S,NaN,490.0

In [1]:
from concat_df import concat_df as cd
files_root_path = 'C:/Users/Ghassen/Documents/Projects/Immobilier/1_Project/Data_assets/Brut/valeursfoncieres-'
list_paths = []
extension = '.txt'
for year in range(2015, 2020):
    list_paths.append(files_root_path + str(year) + extension)
df = cd.concatenate(list_paths)
print(len(df))
df.head()

14880473

,No_disposition,Date_mutation,Nature_mutation,Valeur_fonciere,No_voie,Type_de_voie,Voie,Code_postal,Commune,Code_departement,...,5eme_lot,Surface_Carrez_du_5eme_lot,Nombre_de_lots,Code_type_local,Type_local,Surface_reelle_bati,Nombre_pieces_principales,Nature_culture,Nature_culture_speciale,Surface_terrain
0,2,2015-05-01,Vente,120.0,NaN,NaN,ENTRE LES CHEMINS,1250.0,BOHAS-MEYRIAT-RIGNAT,01,...,NaN,NaN,0,NaN,NaN,NaN,NaN,P,NaN,82.0
1,1,2015-09-01,Vente,12400.0,NaN,NaN,VIGNIEUX,1340.0,JAYAT,01,...,NaN,NaN,0,NaN,NaN,NaN,NaN,AB,NaN,1550.0
2,2,2015-05-01,Vente,110.0,NaN,NaN,ENTRE LES CHEMINS,1250.0,BOHAS-MEYRIAT-RIGNAT,01,...,NaN,NaN,0,NaN,NaN,NaN,NaN,P,NaN,4.0
3,2,2015-07-01,Vente,180.0,NaN,NaN,ENTRE LES CHEMINS,1250.0,BOHAS-MEYRIAT-RIGNAT,01,...,NaN,NaN,0,NaN,NaN,NaN,NaN,P,NaN,298.0
4,1,2015-12-01,Vente,95000.0,5383.0,NaN,LE BOURG,1160.0,PRIAY,01,...,NaN,NaN,0,3.0,Dépendance,0.0,0.0,S,NaN,195.0

In [1]:
import pandas as pd
import time

start_time = time.time()
file_path = 'C:/Users/Ghassen/Documents/Projects/Immobilier/1_Project/Data_assets/Processed/destination_cleaned.csv'
df = pd.read_csv(file_path)
print(len(df))
print((time.time()-start_time))
df.head()

KeyboardInterrupt: